name: archio
description: A starter component that uses Flask framework and SQLite database.
keywords:
  - Flask
  - SQLite
  - Python
  - HTML
  - Gunicorn
secrets:
  flask_env:
    description: Environment in which Flask application runs
    default: production
  gunicorn_workers:
    description: Number of Gunicorn worker processes
    default: 4
  grasswater:
    description: xxxx
    default: yyyy
services:
  app:
    build:
      context: ./
    interfaces:
      main: 5000
    environment:
      FLASK_ENV: '${{ secrets.flask_env }}'
      FLASK_PORT: 5000
    command:
      - sh
      - '-c'
      - >
        gunicorn -w ${{ secrets.gunicorn_workers }} -b 0.0.0.0:${{
        services.app.interfaces.main.port }} "flaskr:create_app()"
    '${{ if architect.environment == ''local'' }}':
      command: python3 app.py
interfaces:
  app:
    url: '${{ services.app.interfaces.main.url }}'
    ingress:
      subdomain: app
